server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Dnjscksdn98@
  jpa:
    show-sql: true